version: '2'

volumes:
  grafana_data: {}

services:
  sortlog-grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=likui
      - GF_USERS_ALLOW_SIGN_UP=false
